### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by sbarbosa115** [GeertjanWielenga/React.js#1]
I can't install the plugin.

**Comment by GeertjanWielenga** [comment]
I can't help you. No information of any kind has been provided, no clue in any way what the problem is.

**Comment by sbarbosa115** [comment]
Hi, excuse me, what is the procedure for install the plug-in ?

**Comment by GeertjanWielenga** [comment]
The same as any other plugin... Just drop me a mail at geertjan.wielenga@oracle.com for help.
